import trackFullHelper from '@/lib/trackFullHelper';

describe('Testing userHelper', () => {
  const track: SpotifyApi.TrackObjectFull = {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X',
          },
          href: 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X',
          id: '4q3ewBCX7sLwd24euuV69X',
          name: 'Bad Bunny',
          type: 'artist',
          uri: 'spotify:artist:4q3ewBCX7sLwd24euuV69X',
        },
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2OHKEe204spO7G7NcbeO2o',
          },
          href: 'https://api.spotify.com/v1/artists/2OHKEe204spO7G7NcbeO2o',
          id: '2OHKEe204spO7G7NcbeO2o',
          name: 'Ñejo',
          type: 'artist',
          uri: 'spotify:artist:2OHKEe204spO7G7NcbeO2o',
        },
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0AdjzZxHJ4MfbImx2rD0Df',
          },
          href: 'https://api.spotify.com/v1/artists/0AdjzZxHJ4MfbImx2rD0Df',
          id: '0AdjzZxHJ4MfbImx2rD0Df',
          name: 'Pj Sin Suela',
          type: 'artist',
          uri: 'spotify:artist:0AdjzZxHJ4MfbImx2rD0Df',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/5tYl7Wcb6TIVB3gs7tuBu8',
      },
      href: 'https://api.spotify.com/v1/albums/5tYl7Wcb6TIVB3gs7tuBu8',
      id: '5tYl7Wcb6TIVB3gs7tuBu8',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273341b4de2eb74ee18d282df0a',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02341b4de2eb74ee18d282df0a',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851341b4de2eb74ee18d282df0a',
          width: 64,
        },
      ],
      name: '¿Cual Es Tu Plan?',
      release_date: '2018-08-17',
      release_date_precision: 'day',
      total_tracks: 1,
      type: 'album',
      uri: 'spotify:album:5tYl7Wcb6TIVB3gs7tuBu8',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X',
        },
        href: 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X',
        id: '4q3ewBCX7sLwd24euuV69X',
        name: 'Bad Bunny',
        type: 'artist',
        uri: 'spotify:artist:4q3ewBCX7sLwd24euuV69X',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2OHKEe204spO7G7NcbeO2o',
        },
        href: 'https://api.spotify.com/v1/artists/2OHKEe204spO7G7NcbeO2o',
        id: '2OHKEe204spO7G7NcbeO2o',
        name: 'Ñejo',
        type: 'artist',
        uri: 'spotify:artist:2OHKEe204spO7G7NcbeO2o',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0AdjzZxHJ4MfbImx2rD0Df',
        },
        href: 'https://api.spotify.com/v1/artists/0AdjzZxHJ4MfbImx2rD0Df',
        id: '0AdjzZxHJ4MfbImx2rD0Df',
        name: 'Pj Sin Suela',
        type: 'artist',
        uri: 'spotify:artist:0AdjzZxHJ4MfbImx2rD0Df',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2ydZrTy8U3kOMOzx20s3dg',
        },
        href: 'https://api.spotify.com/v1/artists/2ydZrTy8U3kOMOzx20s3dg',
        id: '2ydZrTy8U3kOMOzx20s3dg',
        name: 'DJ Nelson',
        type: 'artist',
        uri: 'spotify:artist:2ydZrTy8U3kOMOzx20s3dg',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 243700,
    explicit: true,
    external_ids: {
      isrc: 'QM24S1830276',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/45jM2fuCq0NHD9p7xn0ptd',
    },
    href: 'https://api.spotify.com/v1/tracks/45jM2fuCq0NHD9p7xn0ptd',
    id: '45jM2fuCq0NHD9p7xn0ptd',
    is_local: false,
    name: '¿Cual Es Tu Plan?',
    popularity: 70,
    preview_url:
      'https://p.scdn.co/mp3-preview/20579555384fd759af8a4a55574664b2493c7cac?cid=2bd78767f632439abfd7bad60e551736',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:45jM2fuCq0NHD9p7xn0ptd',
  };

  it('should return valid invisible comic', () => {
    const expected = {
      image: 'https://i.scdn.co/image/ab67616d0000b273341b4de2eb74ee18d282df0a',
      name: '¿Cual Es Tu Plan?',
      album: '¿Cual Es Tu Plan?',
      artists: 'Bad Bunny, Ñejo, Pj Sin Suela, DJ Nelson',
      duration: '4:04',
      id: '45jM2fuCq0NHD9p7xn0ptd',
      type: 'track',
      uri: 'spotify:track:45jM2fuCq0NHD9p7xn0ptd',
    };

    const res = trackFullHelper({ track: track });
    expect(res).toMatchObject(expected);
  });
});
