const albums = [
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4MzJMcHQBl9SIYSjwWn8QW"
              },
              "href": "https://api.spotify.com/v1/artists/4MzJMcHQBl9SIYSjwWn8QW",
              "id": "4MzJMcHQBl9SIYSjwWn8QW",
              "name": "Spiritbox",
              "type": "artist",
              "uri": "spotify:artist:4MzJMcHQBl9SIYSjwWn8QW"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/6cZ39G1mahxDAGfoPzDllb"
      },
      "href": "https://api.spotify.com/v1/albums/6cZ39G1mahxDAGfoPzDllb",
      "id": "6cZ39G1mahxDAGfoPzDllb",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2730006a537a6e19505ca5593eb",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e020006a537a6e19505ca5593eb",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048510006a537a6e19505ca5593eb",
              "width": 64
          }
      ],
      "name": "Eternal Blue",
      "release_date": "2021-09-17",
      "release_date_precision": "day",
      "total_tracks": 12,
      "type": "album",
      "uri": "spotify:album:6cZ39G1mahxDAGfoPzDllb"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1vyhD5VmyZ7KMfW5gqLgo5"
              },
              "href": "https://api.spotify.com/v1/artists/1vyhD5VmyZ7KMfW5gqLgo5",
              "id": "1vyhD5VmyZ7KMfW5gqLgo5",
              "name": "J Balvin",
              "type": "artist",
              "uri": "spotify:artist:1vyhD5VmyZ7KMfW5gqLgo5"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/49Et8wid3L8iKof9lu78SS"
      },
      "href": "https://api.spotify.com/v1/albums/49Et8wid3L8iKof9lu78SS",
      "id": "49Et8wid3L8iKof9lu78SS",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273ea755cf5e2a1513e9b2c497d",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02ea755cf5e2a1513e9b2c497d",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851ea755cf5e2a1513e9b2c497d",
              "width": 64
          }
      ],
      "name": "Tu Veneno",
      "release_date": "2021-03-19",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:49Et8wid3L8iKof9lu78SS"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/77ziqFxp5gaInVrF2lj4ht"
              },
              "href": "https://api.spotify.com/v1/artists/77ziqFxp5gaInVrF2lj4ht",
              "id": "77ziqFxp5gaInVrF2lj4ht",
              "name": "Sech",
              "type": "artist",
              "uri": "spotify:artist:77ziqFxp5gaInVrF2lj4ht"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4SsVbpTthjScTS7U2hmr1X"
              },
              "href": "https://api.spotify.com/v1/artists/4SsVbpTthjScTS7U2hmr1X",
              "id": "4SsVbpTthjScTS7U2hmr1X",
              "name": "Arcangel",
              "type": "artist",
              "uri": "spotify:artist:4SsVbpTthjScTS7U2hmr1X"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/7fFVkxqYbtA4xO4BSFs8vt"
      },
      "href": "https://api.spotify.com/v1/albums/7fFVkxqYbtA4xO4BSFs8vt",
      "id": "7fFVkxqYbtA4xO4BSFs8vt",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2739a1b9a69bf0a6e0ee6095188",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e029a1b9a69bf0a6e0ee6095188",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048519a1b9a69bf0a6e0ee6095188",
              "width": 64
          }
      ],
      "name": "Te Acuerdas",
      "release_date": "2021-03-19",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:7fFVkxqYbtA4xO4BSFs8vt"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/7iK8PXO48WeuP03g8YR51W"
              },
              "href": "https://api.spotify.com/v1/artists/7iK8PXO48WeuP03g8YR51W",
              "id": "7iK8PXO48WeuP03g8YR51W",
              "name": "Myke Towers",
              "type": "artist",
              "uri": "spotify:artist:7iK8PXO48WeuP03g8YR51W"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/4HKm0BAbVpTdwb1dru6uem"
      },
      "href": "https://api.spotify.com/v1/albums/4HKm0BAbVpTdwb1dru6uem",
      "id": "4HKm0BAbVpTdwb1dru6uem",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27386686732ed5779f3c4284305",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0286686732ed5779f3c4284305",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485186686732ed5779f3c4284305",
              "width": 64
          }
      ],
      "name": "CUENTA",
      "release_date": "2021-03-18",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:4HKm0BAbVpTdwb1dru6uem"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2DspEsT7UXGKd2VaaedgG4"
              },
              "href": "https://api.spotify.com/v1/artists/2DspEsT7UXGKd2VaaedgG4",
              "id": "2DspEsT7UXGKd2VaaedgG4",
              "name": "Alex Rose",
              "type": "artist",
              "uri": "spotify:artist:2DspEsT7UXGKd2VaaedgG4"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1mcTU81TzQhprhouKaTkpq"
              },
              "href": "https://api.spotify.com/v1/artists/1mcTU81TzQhprhouKaTkpq",
              "id": "1mcTU81TzQhprhouKaTkpq",
              "name": "Rauw Alejandro",
              "type": "artist",
              "uri": "spotify:artist:1mcTU81TzQhprhouKaTkpq"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/14FrKuNUxsU8eEooOVW1DC"
      },
      "href": "https://api.spotify.com/v1/albums/14FrKuNUxsU8eEooOVW1DC",
      "id": "14FrKuNUxsU8eEooOVW1DC",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2735f585b216b19318a6d3445e8",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e025f585b216b19318a6d3445e8",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048515f585b216b19318a6d3445e8",
              "width": 64
          }
      ],
      "name": "Me Fije",
      "release_date": "2021-03-18",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:14FrKuNUxsU8eEooOVW1DC"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4bw2Am3p9ji3mYsXNXtQcd"
              },
              "href": "https://api.spotify.com/v1/artists/4bw2Am3p9ji3mYsXNXtQcd",
              "id": "4bw2Am3p9ji3mYsXNXtQcd",
              "name": "Piso 21",
              "type": "artist",
              "uri": "spotify:artist:4bw2Am3p9ji3mYsXNXtQcd"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/4ARUAVQnIDB02yVO8uvaJE"
      },
      "href": "https://api.spotify.com/v1/albums/4ARUAVQnIDB02yVO8uvaJE",
      "id": "4ARUAVQnIDB02yVO8uvaJE",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2739a74860d7918c8e38c5220cf",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e029a74860d7918c8e38c5220cf",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048519a74860d7918c8e38c5220cf",
              "width": 64
          }
      ],
      "name": "El Amor En Los Tiempos Del Perreo",
      "release_date": "2021-03-18",
      "release_date_precision": "day",
      "total_tracks": 15,
      "type": "album",
      "uri": "spotify:album:4ARUAVQnIDB02yVO8uvaJE"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/5bSfBBCxY8QAk4Pifveisz"
              },
              "href": "https://api.spotify.com/v1/artists/5bSfBBCxY8QAk4Pifveisz",
              "id": "5bSfBBCxY8QAk4Pifveisz",
              "name": "La Arrolladora Banda El Limón De Rene Camacho",
              "type": "artist",
              "uri": "spotify:artist:5bSfBBCxY8QAk4Pifveisz"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/2aN7waichOQyWVoEECWerE"
      },
      "href": "https://api.spotify.com/v1/albums/2aN7waichOQyWVoEECWerE",
      "id": "2aN7waichOQyWVoEECWerE",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27371fbee42c31f9a1b7c39acbb",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0271fbee42c31f9a1b7c39acbb",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485171fbee42c31f9a1b7c39acbb",
              "width": 64
          }
      ],
      "name": "En Contra De Mi Voluntad",
      "release_date": "2021-03-19",
      "release_date_precision": "day",
      "total_tracks": 14,
      "type": "album",
      "uri": "spotify:album:2aN7waichOQyWVoEECWerE"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1bAftSH8umNcGZ0uyV7LMg"
              },
              "href": "https://api.spotify.com/v1/artists/1bAftSH8umNcGZ0uyV7LMg",
              "id": "1bAftSH8umNcGZ0uyV7LMg",
              "name": "Duki",
              "type": "artist",
              "uri": "spotify:artist:1bAftSH8umNcGZ0uyV7LMg"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/05XZWDj3tPhgwD3zQw43X7"
      },
      "href": "https://api.spotify.com/v1/albums/05XZWDj3tPhgwD3zQw43X7",
      "id": "05XZWDj3tPhgwD3zQw43X7",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273ed5d83921bacacb3571acb26",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02ed5d83921bacacb3571acb26",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851ed5d83921bacacb3571acb26",
              "width": 64
          }
      ],
      "name": "Chico Estrella",
      "release_date": "2021-03-15",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:05XZWDj3tPhgwD3zQw43X7"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/7rOlQwf8OuFLFQp4aydjBt"
              },
              "href": "https://api.spotify.com/v1/artists/7rOlQwf8OuFLFQp4aydjBt",
              "id": "7rOlQwf8OuFLFQp4aydjBt",
              "name": "Paloma Mami",
              "type": "artist",
              "uri": "spotify:artist:7rOlQwf8OuFLFQp4aydjBt"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/4jfOmy33i7nM0gW5zPslJK"
      },
      "href": "https://api.spotify.com/v1/albums/4jfOmy33i7nM0gW5zPslJK",
      "id": "4jfOmy33i7nM0gW5zPslJK",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273b7b03075a7d337cfac90baf8",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02b7b03075a7d337cfac90baf8",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851b7b03075a7d337cfac90baf8",
              "width": 64
          }
      ],
      "name": "Sueños de Dalí",
      "release_date": "2021-03-18",
      "release_date_precision": "day",
      "total_tracks": 11,
      "type": "album",
      "uri": "spotify:album:4jfOmy33i7nM0gW5zPslJK"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4F4pp8NUW08JuXwnoxglpN"
              },
              "href": "https://api.spotify.com/v1/artists/4F4pp8NUW08JuXwnoxglpN",
              "id": "4F4pp8NUW08JuXwnoxglpN",
              "name": "Bad Gyal",
              "type": "artist",
              "uri": "spotify:artist:4F4pp8NUW08JuXwnoxglpN"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/7IJ4Cok2sQKI7JgpPyDIWr"
      },
      "href": "https://api.spotify.com/v1/albums/7IJ4Cok2sQKI7JgpPyDIWr",
      "id": "7IJ4Cok2sQKI7JgpPyDIWr",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2737a0b5c826689bee750c3605f",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e027a0b5c826689bee750c3605f",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048517a0b5c826689bee750c3605f",
              "width": 64
          }
      ],
      "name": "Warm Up",
      "release_date": "2021-03-18",
      "release_date_precision": "day",
      "total_tracks": 8,
      "type": "album",
      "uri": "spotify:album:7IJ4Cok2sQKI7JgpPyDIWr"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/7q9P9jadKe86eEavevbEvK"
              },
              "href": "https://api.spotify.com/v1/artists/7q9P9jadKe86eEavevbEvK",
              "id": "7q9P9jadKe86eEavevbEvK",
              "name": "Gianluca",
              "type": "artist",
              "uri": "spotify:artist:7q9P9jadKe86eEavevbEvK"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0NnUMWDCDi1snuMja6IdxH"
              },
              "href": "https://api.spotify.com/v1/artists/0NnUMWDCDi1snuMja6IdxH",
              "id": "0NnUMWDCDi1snuMja6IdxH",
              "name": "Harry Nach",
              "type": "artist",
              "uri": "spotify:artist:0NnUMWDCDi1snuMja6IdxH"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/3MiJv4EixolUevdX2QeHGw"
      },
      "href": "https://api.spotify.com/v1/albums/3MiJv4EixolUevdX2QeHGw",
      "id": "3MiJv4EixolUevdX2QeHGw",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273430c1e13234b320049991d71",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02430c1e13234b320049991d71",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851430c1e13234b320049991d71",
              "width": 64
          }
      ],
      "name": "triste y vacía",
      "release_date": "2021-03-19",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:3MiJv4EixolUevdX2QeHGw"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/7K9rdoOJSiKXoVXPlSkGKT"
              },
              "href": "https://api.spotify.com/v1/artists/7K9rdoOJSiKXoVXPlSkGKT",
              "id": "7K9rdoOJSiKXoVXPlSkGKT",
              "name": "Paty Cantú",
              "type": "artist",
              "uri": "spotify:artist:7K9rdoOJSiKXoVXPlSkGKT"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1DxLCyH42yaHKGK3cl5bvG"
              },
              "href": "https://api.spotify.com/v1/artists/1DxLCyH42yaHKGK3cl5bvG",
              "id": "1DxLCyH42yaHKGK3cl5bvG",
              "name": "Maria Becerra",
              "type": "artist",
              "uri": "spotify:artist:1DxLCyH42yaHKGK3cl5bvG"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/3nW0X7PWKLo6pK69T28trN"
      },
      "href": "https://api.spotify.com/v1/albums/3nW0X7PWKLo6pK69T28trN",
      "id": "3nW0X7PWKLo6pK69T28trN",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2731ce0af82a3dc7f574034c5bb",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e021ce0af82a3dc7f574034c5bb",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048511ce0af82a3dc7f574034c5bb",
              "width": 64
          }
      ],
      "name": "Si Yo Fuera Tú",
      "release_date": "2021-03-19",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:3nW0X7PWKLo6pK69T28trN"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2LaHOt5YZlFAhZ22KDI5fS"
              },
              "href": "https://api.spotify.com/v1/artists/2LaHOt5YZlFAhZ22KDI5fS",
              "id": "2LaHOt5YZlFAhZ22KDI5fS",
              "name": "Ben Carrillo",
              "type": "artist",
              "uri": "spotify:artist:2LaHOt5YZlFAhZ22KDI5fS"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/3933M7LLB4vQZvIUdQYDxF"
      },
      "href": "https://api.spotify.com/v1/albums/3933M7LLB4vQZvIUdQYDxF",
      "id": "3933M7LLB4vQZvIUdQYDxF",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27339a11a3f3d930aaee99691b9",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0239a11a3f3d930aaee99691b9",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485139a11a3f3d930aaee99691b9",
              "width": 64
          }
      ],
      "name": "Crecimiento, Demos",
      "release_date": "2021-03-18",
      "release_date_precision": "day",
      "total_tracks": 6,
      "type": "album",
      "uri": "spotify:album:3933M7LLB4vQZvIUdQYDxF"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/6Itjwvv5YmsC8ZcI5N4Jux"
              },
              "href": "https://api.spotify.com/v1/artists/6Itjwvv5YmsC8ZcI5N4Jux",
              "id": "6Itjwvv5YmsC8ZcI5N4Jux",
              "name": "Sael",
              "type": "artist",
              "uri": "spotify:artist:6Itjwvv5YmsC8ZcI5N4Jux"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1GKIlPFdcewHtpDVCQ8zmJ"
              },
              "href": "https://api.spotify.com/v1/artists/1GKIlPFdcewHtpDVCQ8zmJ",
              "id": "1GKIlPFdcewHtpDVCQ8zmJ",
              "name": "Brray",
              "type": "artist",
              "uri": "spotify:artist:1GKIlPFdcewHtpDVCQ8zmJ"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2QUvtLq6oQaX0LNsYY2fas"
              },
              "href": "https://api.spotify.com/v1/artists/2QUvtLq6oQaX0LNsYY2fas",
              "id": "2QUvtLq6oQaX0LNsYY2fas",
              "name": "Cauty",
              "type": "artist",
              "uri": "spotify:artist:2QUvtLq6oQaX0LNsYY2fas"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/4V2THb8uH6o2Qy70fBbDhq"
      },
      "href": "https://api.spotify.com/v1/albums/4V2THb8uH6o2Qy70fBbDhq",
      "id": "4V2THb8uH6o2Qy70fBbDhq",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27337d11f38888ad8ea1d931c01",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0237d11f38888ad8ea1d931c01",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485137d11f38888ad8ea1d931c01",
              "width": 64
          }
      ],
      "name": "Sin Mente",
      "release_date": "2021-03-16",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:4V2THb8uH6o2Qy70fBbDhq"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0C8ZW7ezQVs4URX5aX7Kqx"
              },
              "href": "https://api.spotify.com/v1/artists/0C8ZW7ezQVs4URX5aX7Kqx",
              "id": "0C8ZW7ezQVs4URX5aX7Kqx",
              "name": "Selena Gomez",
              "type": "artist",
              "uri": "spotify:artist:0C8ZW7ezQVs4URX5aX7Kqx"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/2jGa3OwXatFYQAIS7OV7k9"
      },
      "href": "https://api.spotify.com/v1/albums/2jGa3OwXatFYQAIS7OV7k9",
      "id": "2jGa3OwXatFYQAIS7OV7k9",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2738b11b0be988e17da2799b94d",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e028b11b0be988e17da2799b94d",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048518b11b0be988e17da2799b94d",
              "width": 64
          }
      ],
      "name": "Revelación - EP",
      "release_date": "2021-03-12",
      "release_date_precision": "day",
      "total_tracks": 7,
      "type": "album",
      "uri": "spotify:album:2jGa3OwXatFYQAIS7OV7k9"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/5hdhHgpxyniooUiQVaPxQ0"
              },
              "href": "https://api.spotify.com/v1/artists/5hdhHgpxyniooUiQVaPxQ0",
              "id": "5hdhHgpxyniooUiQVaPxQ0",
              "name": "Nio Garcia",
              "type": "artist",
              "uri": "spotify:artist:5hdhHgpxyniooUiQVaPxQ0"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1fux65HMCBvfJHqlBc4Nno"
              },
              "href": "https://api.spotify.com/v1/artists/1fux65HMCBvfJHqlBc4Nno",
              "id": "1fux65HMCBvfJHqlBc4Nno",
              "name": "Casper Magico",
              "type": "artist",
              "uri": "spotify:artist:1fux65HMCBvfJHqlBc4Nno"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1i8SpTcr7yvPOmcqrbnVXY"
              },
              "href": "https://api.spotify.com/v1/artists/1i8SpTcr7yvPOmcqrbnVXY",
              "id": "1i8SpTcr7yvPOmcqrbnVXY",
              "name": "Ozuna",
              "type": "artist",
              "uri": "spotify:artist:1i8SpTcr7yvPOmcqrbnVXY"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/1rQpXDegLbNBpe0fshpeKa"
      },
      "href": "https://api.spotify.com/v1/albums/1rQpXDegLbNBpe0fshpeKa",
      "id": "1rQpXDegLbNBpe0fshpeKa",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273cc8f0a311223df53274d69a2",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02cc8f0a311223df53274d69a2",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851cc8f0a311223df53274d69a2",
              "width": 64
          }
      ],
      "name": "Travesuras (Remix)",
      "release_date": "2021-03-11",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:1rQpXDegLbNBpe0fshpeKa"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0EFisYRi20PTADoJrifHrz"
              },
              "href": "https://api.spotify.com/v1/artists/0EFisYRi20PTADoJrifHrz",
              "id": "0EFisYRi20PTADoJrifHrz",
              "name": "Jhay Cortez",
              "type": "artist",
              "uri": "spotify:artist:0EFisYRi20PTADoJrifHrz"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/4qLn9tjRhGQLjImUMTjOMz"
      },
      "href": "https://api.spotify.com/v1/albums/4qLn9tjRhGQLjImUMTjOMz",
      "id": "4qLn9tjRhGQLjImUMTjOMz",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273571a44d8528ceb110ed3b16e",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02571a44d8528ceb110ed3b16e",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851571a44d8528ceb110ed3b16e",
              "width": 64
          }
      ],
      "name": "Christian Dior",
      "release_date": "2021-03-12",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:4qLn9tjRhGQLjImUMTjOMz"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1mcTU81TzQhprhouKaTkpq"
              },
              "href": "https://api.spotify.com/v1/artists/1mcTU81TzQhprhouKaTkpq",
              "id": "1mcTU81TzQhprhouKaTkpq",
              "name": "Rauw Alejandro",
              "type": "artist",
              "uri": "spotify:artist:1mcTU81TzQhprhouKaTkpq"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/6cEuCEZu7PAE9ZSzLLc2oQ"
              },
              "href": "https://api.spotify.com/v1/artists/6cEuCEZu7PAE9ZSzLLc2oQ",
              "id": "6cEuCEZu7PAE9ZSzLLc2oQ",
              "name": "R3HAB",
              "type": "artist",
              "uri": "spotify:artist:6cEuCEZu7PAE9ZSzLLc2oQ"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/1UC5jCthGQNO7vgtdLau7R"
      },
      "href": "https://api.spotify.com/v1/albums/1UC5jCthGQNO7vgtdLau7R",
      "id": "1UC5jCthGQNO7vgtdLau7R",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2735dcf58bcd799d5a144ab80e9",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e025dcf58bcd799d5a144ab80e9",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048515dcf58bcd799d5a144ab80e9",
              "width": 64
          }
      ],
      "name": "Algo Mágico (R3HAB Remix)",
      "release_date": "2021-03-11",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:1UC5jCthGQNO7vgtdLau7R"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/5H1nN1SzW0qNeUEZvuXjAj"
              },
              "href": "https://api.spotify.com/v1/artists/5H1nN1SzW0qNeUEZvuXjAj",
              "id": "5H1nN1SzW0qNeUEZvuXjAj",
              "name": "Danny Ocean",
              "type": "artist",
              "uri": "spotify:artist:5H1nN1SzW0qNeUEZvuXjAj"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/14zUHaJZo1mnYtn6IBRaRP"
              },
              "href": "https://api.spotify.com/v1/artists/14zUHaJZo1mnYtn6IBRaRP",
              "id": "14zUHaJZo1mnYtn6IBRaRP",
              "name": "Justin Quiles",
              "type": "artist",
              "uri": "spotify:artist:14zUHaJZo1mnYtn6IBRaRP"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/1SkjS616tH0mUti7wGYUGB"
      },
      "href": "https://api.spotify.com/v1/albums/1SkjS616tH0mUti7wGYUGB",
      "id": "1SkjS616tH0mUti7wGYUGB",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27372b415966c6e58c38ae66954",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0272b415966c6e58c38ae66954",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485172b415966c6e58c38ae66954",
              "width": 64
          }
      ],
      "name": "Cuántas veces",
      "release_date": "2021-03-11",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:1SkjS616tH0mUti7wGYUGB"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
              },
              "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
              "id": "0TnOYISbd1XYRBk9myaseg",
              "name": "Pitbull",
              "type": "artist",
              "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/329e4yvIujISKGKz1BZZbO"
              },
              "href": "https://api.spotify.com/v1/artists/329e4yvIujISKGKz1BZZbO",
              "id": "329e4yvIujISKGKz1BZZbO",
              "name": "Farruko",
              "type": "artist",
              "uri": "spotify:artist:329e4yvIujISKGKz1BZZbO"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0b2GL7Y02vu50qieoQmw1w"
              },
              "href": "https://api.spotify.com/v1/artists/0b2GL7Y02vu50qieoQmw1w",
              "id": "0b2GL7Y02vu50qieoQmw1w",
              "name": "IAmChino",
              "type": "artist",
              "uri": "spotify:artist:0b2GL7Y02vu50qieoQmw1w"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/23JpPGYxFaXVcuZABPm7JI"
      },
      "href": "https://api.spotify.com/v1/albums/23JpPGYxFaXVcuZABPm7JI",
      "id": "23JpPGYxFaXVcuZABPm7JI",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2736e6f2f742ef88e94edef99e4",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e026e6f2f742ef88e94edef99e4",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048516e6f2f742ef88e94edef99e4",
              "width": 64
          }
      ],
      "name": "Ten Cuidado",
      "release_date": "2021-03-12",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:23JpPGYxFaXVcuZABPm7JI"
  }
];

export default albums;